<?php

$UsernameID=$dbUsername['ID'];
$BranchID=$dbUsername['BranchID'];
$DOB=$dbUsername['DOB'];
$Gender=$dbUsername['Gender'];
$FBID=$dbUsername['FBID'];
$Phone=$dbUsername['Phone'];
$Email=$dbUsername['Email'];
$Type=$dbUsername['Type'];
$Username_Code=$dbUsername['Username_Code'];
$Username=$dbUsername['Username'];
$Password=$dbUsername['Password'];
$Firstname=$dbUsername['Firstname'];
$Lastname=$dbUsername['Lastname'];
$Position=$dbUsername['Position'];
$Business_Name=$dbUsername['Business_Name'];
$GAddress=$dbUsername['GAddress'];
$Lat=$dbUsername['Lat'];
$Lng=$dbUsername['Lng'];
$Telephone=$dbUsername['Telephone'];
$Status=$dbUsername['Status'];
$Remark=$dbUsername['Remark'];
$Package=$dbUsername['Package'];
$Created=$dbUsername['Created'];
$Permission_POS=$dbUsername['Permission_POS'];
$Permission_Report=$dbUsername['Permission_Report'];
$Permission_Kitchen=$dbUsername['Permission_Kitchen'];
$Permission_Stock=$dbUsername['Permission_Stock'];
$Permission_Member=$dbUsername['Permission_Member'];
$Permission_Promotion=$dbUsername['Permission_Promotion'];
$Permission_CheckIn=$dbUsername['Permission_CheckIn'];

?>